import Head from 'next/head'
import { useContext } from 'react'
import { EthereumContext } from '../src/context/EthereumContext'

export default function Home() {

  const { accounts } = useContext(EthereumContext);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{accounts[0]}</h1>
      </main>
    </>
  )
}
